cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  - PATH="$GOPATH/bin:$PATH"
  - go get -v -d ./...

stages:
  - test
  #- build
#  - smoke-test
#  - release

unit_tests:
  stage: test
  image: golang:1.18
  coverage: '/total:\s+\(statements\)\s+(\d+.\d+\%)/'
  script:
    - go install gotest.tools/gotestsum@latest
    - gotestsum  --junitfile report.xml --format testname  -- -coverprofile=coverage.out -timeout 15m ./...
    - cat coverage.out | grep -v ".pb.go"|grep -v ".gw.go"|grep -v "erc20.go"|grep -v "oppy_transfer.go" > cover.out
    - go tool cover -func=cover.out

  artifacts:
    when: always
    reports:
      junit: report.xml
    expire_in: 1 week

lint_code:
  image: golangci/golangci-lint
  stage: test
  before_script:
    - go get mvdan.cc/gofumpt
  script:
    - golangci-lint run -v --timeout 3600s -c ./.golangci.yml
